version: '3'
services:
  database:
    build: docker/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xaquiz
      MYSQL_DATABASE: xaquiz
      MYSQL_USER: root
      MYSQL_PASSWORD: xaquiz

  web:
    build: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    links:
      - php
    depends_on:
      - php
      - redis

  redis:
    build: docker/redis
    ports:
      - "6379:6379"

  php:
    build: docker/php
    volumes:
      - ./:/var/www
    expose:
      - "9000"
